import { prisma } from "@/lib/prisma";
import { GoogleGenAI } from "@google/genai";

function getClient() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY is not configured");
  return new GoogleGenAI({ apiKey });
}

const TOPICS = [
  "Son teknoloji haberleri ve yazilim dunyasindaki gelismeler",
  "Yapay zekanin medya ve reklamcilik sektorune etkileri",
  "Dijital pazarlama ve gerilla pazarlama stratejileri",
  "E-ticaret siteleri icin donusum artirma taktikleri",
  "Siber guvenlik onlemleri ve kurumsal verilerin korunmasi",
  "Web gelistirme dunyasindaki en yeni trendler ve frameworkler",
  "Sosyal medya algoritmalari ve marka bilinirligi artirma",
];

function getRandomTopic() {
  return TOPICS[Math.floor(Math.random() * TOPICS.length)];
}

function generateSlug(title: string) {
  return title
    .toLowerCase()
    .replace(/\u011f/g, "g").replace(/\u00fc/g, "u").replace(/\u015f/g, "s")
    .replace(/\u0131/g, "i").replace(/\u00f6/g, "o").replace(/\u00e7/g, "c")
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .trim() +
    "-" +
    Math.random().toString(36).substring(2, 6);
}

export async function generateAndPublishBlog() {
  console.log(`[${new Date().toISOString()}] Otonom Blog Uretimi Tetiklendi...`);

  const topic = getRandomTopic();
  const prompt = `Sen "Cicekana Teknoloji & Medya" isimli kurumsal bir firman\u0131n ba\u015f yazar\u0131 ve teknoloji uzman\u0131s\u0131n.
G\u00f6rev: A\u015fa\u011f\u0131daki konu hakk\u0131nda olduk\u00e7a g\u00fcncel, SEO uyumlu, ilgi \u00e7ekici ve bilgilendirici bir blog yaz\u0131s\u0131 olu\u015ftur.
Konu: ${topic}
Kurallar:
1. \u0130lk sat\u0131r mutlaka "# " ile ba\u015flayan yarat\u0131c\u0131 ve dikkat \u00e7ekici bir ba\u015fl\u0131k olmal\u0131.
2. Yaz\u0131 dili profesyonel ama anla\u015f\u0131l\u0131r (kurumsal blog dili) olmal\u0131.
3. \u0130\u00e7erik markdown format\u0131nda olmal\u0131. Alt ba\u015fl\u0131klar (##, ###) kullan.
4. Yaz\u0131 en az 400-500 kelime civar\u0131nda dolgun bir i\u00e7erik olmal\u0131.
5. Sonunda mutlaka Cicekana Teknoloji & Medya'n\u0131n sundu\u011fu ilgili hizmetlere (\u00f6rne\u011fin e-ticaret, yaz\u0131l\u0131m, reklam) ufak bir \u00e7a\u011fr\u0131 (call-to-action) yap.`;

  const ai = getClient();

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
    });
    let content = response.text || "";

    let title = "Guncel Teknoloji ve Medya Haberleri";
    const titleMatch = content.match(/^#\s+(.+)$/m);
    if (titleMatch && titleMatch[1]) {
      title = titleMatch[1].trim();
      content = content.replace(/^#\s+.+\n*/m, "");
    }

    const slug = generateSlug(title);

    let author = await prisma.user.findFirst({ where: { role: "SUPER_ADMIN" } });
    if (!author) {
      author = await prisma.user.create({
        data: {
          email: "admin@cicekana.com",
          name: "Cicekana Admin",
          role: "SUPER_ADMIN",
          passwordHash: "AUTOGENERATED",
        },
      });
    }

    const post = await prisma.blogPost.create({
      data: {
        title,
        slug,
        content: { body: content },
        excerpt: content.substring(0, 150).replace(/[#*`]/g, "") + "...",
        category: "Teknoloji & Medya",
        status: "PUBLISHED",
        publishedAt: new Date(),
        authorId: author.id,
        readTime: Math.max(3, Math.floor(content.split(" ").length / 200)),
        metaDescription: title.substring(0, 160),
      },
    });

    return { success: true, post };
  } catch (error: any) {
    console.error("Blog Uretim Hatasi:", error);
    throw error;
  }
}
