"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, Plus, Search } from "lucide-react";

type Plan = { id: string; name: string; slug: string; shortDescription: string; fullContentHtml: string; features: unknown; imageUrl: string | null; priceMonthly: number; isActive: boolean; displayOrder: number; updatedAt: string };
type Form = Omit<Plan, "id" | "updatedAt">;
const emptyForm: Form = { name: "", slug: "", shortDescription: "", fullContentHtml: "", features: [], imageUrl: "", priceMonthly: 0, isActive: false, displayOrder: 0 };

function slugify(value: string) { return value.toLocaleLowerCase("tr-TR").replace(/[çğıöşü]/g, (c) => ({ ç: "c", ğ: "g", ı: "i", ö: "o", ş: "s", ü: "u" })[c] ?? c).normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
function formatPrice(cents: number) { return new Intl.NumberFormat("tr-TR", { style: "currency", currency: "TRY" }).format(cents / 100); }

export default function AdminProductsPage() {
  const [plans, setPlans] = useState<Plan[]>([]); const [query, setQuery] = useState(""); const [editing, setEditing] = useState<Plan | null>(null); const [form, setForm] = useState<Form>(emptyForm); const [slugEdited, setSlugEdited] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  async function load() { setLoading(true); const response = await fetch("/api/admin/plans"); const data = await response.json(); if (response.ok) setPlans(data); else setError(data.error ?? "Ürünler yüklenemedi"); setLoading(false); }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => plans.filter((plan) => `${plan.name} ${plan.slug}`.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"))), [plans, query]);
  function openForm(plan?: Plan) { setEditing(plan ?? null); setForm(plan ? { ...plan, priceMonthly: plan.priceMonthly / 100, features: plan.features } : emptyForm); setSlugEdited(Boolean(plan)); setError(""); }
  function update<K extends keyof Form>(key: K, value: Form[K]) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (!form.name.trim() || !form.shortDescription.trim() || form.priceMonthly <= 0) { setError("Ürün adı, kısa açıklama ve 0'dan büyük fiyat zorunludur."); return; } setSaving(true); const payload = { ...form, slug: form.slug || slugify(form.name), priceMonthly: Math.round(Number(form.priceMonthly) * 100), features: form.features || [] }; const response = await fetch(editing ? `/api/admin/plans/${editing.id}` : "/api/admin/plans", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) setError(data.error ?? "Kaydetme başarısız."); else { setEditing(null); setForm(emptyForm); await load(); } setSaving(false); }
  return <div className="flex flex-col gap-6">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/admin" className="mb-2 inline-flex items-center gap-2 text-sm text-corp-gray hover:text-corp-teal"><ArrowLeft /> Admin</Link><h1 className="font-display text-2xl font-bold text-corp-charcoal">Abonelik Ürünleri</h1><p className="text-sm text-corp-gray">Planları oluşturun ve yayın durumlarını yönetin.</p></div><button onClick={() => openForm()} className="inline-flex items-center gap-2 rounded-xl bg-corp-teal px-4 py-2.5 text-sm font-semibold text-white"><Plus /> Yeni Ürün Ekle</button></div>
    <div className="rounded-3xl border border-corp-border bg-white p-5 shadow-luxury"><div className="relative mb-5 max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-corp-gray" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="İsim veya slug ara..." className="w-full rounded-xl border border-corp-border py-2.5 pl-10 pr-4 text-sm outline-none focus:border-corp-teal" /></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-corp-border text-xs uppercase tracking-wider text-corp-gray"><th className="p-3">Ürün</th><th className="p-3">Slug</th><th className="p-3">Aylık fiyat</th><th className="p-3">Durum</th><th className="p-3">Güncellendi</th><th className="p-3" /></tr></thead><tbody>{loading ? <tr><td colSpan={6} className="p-8 text-center text-corp-gray">Yükleniyor...</td></tr> : filtered.map((plan) => <tr key={plan.id} className="border-b border-corp-border last:border-0"><td className="p-3"><div className="font-semibold text-corp-charcoal">{plan.name}</div><div className="text-xs text-corp-gray">{plan.shortDescription}</div></td><td className="p-3 font-mono text-xs text-corp-gray">{plan.slug}</td><td className="p-3 font-medium">{formatPrice(plan.priceMonthly)}</td><td className="p-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${plan.isActive ? "bg-corp-teal/10 text-corp-teal" : "bg-corp-surface text-corp-gray"}`}>{plan.isActive ? "Aktif" : "Pasif"}</span></td><td className="p-3 text-corp-gray">{new Date(plan.updatedAt).toLocaleDateString("tr-TR")}</td><td className="p-3 text-right"><button onClick={() => openForm(plan)} className="rounded-lg border border-corp-border px-3 py-1.5 text-sm hover:border-corp-teal hover:text-corp-teal">Düzenle</button></td></tr>)}</tbody></table></div></div>
    {(editing || form === emptyForm) && <div className="rounded-3xl border border-corp-border bg-white p-6 shadow-luxury"><h2 className="mb-5 text-lg font-bold">{editing ? "Ürünü Düzenle" : "Yeni Ürün"}</h2><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><label>Ürün Adı<input required value={form.name} onChange={(e) => { update("name", e.target.value); if (!slugEdited) update("slug", slugify(e.target.value)); }} className="mt-1 w-full rounded-xl border border-corp-border p-2.5" /></label><label>Slug<input required value={form.slug} onChange={(e) => { setSlugEdited(true); update("slug", slugify(e.target.value)); }} className="mt-1 w-full rounded-xl border border-corp-border p-2.5" /></label><label className="md:col-span-2">Kısa Açıklama <span className="text-xs text-corp-gray">{form.shortDescription.length}/200</span><input required maxLength={200} value={form.shortDescription} onChange={(e) => update("shortDescription", e.target.value)} className="mt-1 w-full rounded-xl border border-corp-border p-2.5" /></label><label>Aylık Fiyat (TL)<input required min="0.01" step="0.01" type="number" value={form.priceMonthly || ""} onChange={(e) => update("priceMonthly", Number(e.target.value))} className="mt-1 w-full rounded-xl border border-corp-border p-2.5" /></label><label>Sıralama<input min="0" type="number" value={form.displayOrder} onChange={(e) => update("displayOrder", Number(e.target.value))} className="mt-1 w-full rounded-xl border border-corp-border p-2.5" /></label><label className="md:col-span-2">İçerik<textarea value={form.fullContentHtml} onChange={(e) => update("fullContentHtml", e.target.value)} className="mt-1 min-h-24 w-full rounded-xl border border-corp-border p-2.5" /></label><label>Görsel URL<input type="url" value={form.imageUrl ?? ""} onChange={(e) => update("imageUrl", e.target.value)} className="mt-1 w-full rounded-xl border border-corp-border p-2.5" /></label><label>Özellikler (JSON veya metin)<textarea value={Array.isArray(form.features) ? form.features.join("\n") : String(form.features ?? "")} onChange={(e) => update("features", e.target.value.split("\n").filter(Boolean))} className="mt-1 min-h-20 w-full rounded-xl border border-corp-border p-2.5" /></label><label className="flex items-center gap-2"><input type="checkbox" checked={form.isActive} onChange={(e) => update("isActive", e.target.checked)} /> Yayında (Aktif)</label>{error && <p className="md:col-span-2 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex gap-3 md:col-span-2"><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-corp-teal px-5 py-2.5 font-semibold text-white disabled:opacity-60">{saving && <Check />} {saving ? "Kaydediliyor..." : "Kaydet"}</button><button type="button" onClick={() => { setEditing(null); setForm(emptyForm); }} className="rounded-xl border border-corp-border px-5 py-2.5">İptal</button></div></form></div>}
  </div>;
}
