"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ImagePlus, Plus, Search, Trash2, X } from "lucide-react";
import { PLAN_ICON_NAMES, getPlanIcon } from "@/lib/plan-icons";

type Tier = { id?: string; name: string; description?: string | null; priceMonthly: number; badge: string | null; isRecommended: boolean; displayOrder: number; isActive: boolean; features: unknown };
type Item = { icon?: string; title: string; description: string; badge?: string };
type Plan = { id: string; name: string; slug: string; shortDescription: string; fullContentHtml: string; features: unknown; imageUrl: string | null; priceMonthly: number; isActive: boolean; displayOrder: number; updatedAt: string; tiers: Tier[]; tagline?: string; heroHeadline?: string; heroSubheadline?: string; heroMockupUrl?: string; trustPoints?: unknown; stats?: unknown; benefits?: unknown; highlights?: unknown; steps?: unknown; faqs?: unknown; vatNote?: string; disclaimer?: string; secondaryCtaLabel?: string; secondaryCtaUrl?: string };
type FormTier = Omit<Tier, "priceMonthly" | "features"> & { priceMonthly: number; features: string[] };
type Form = Omit<Plan, "id" | "updatedAt" | "tiers" | "priceMonthly" | "fullContentHtml" | "features" | "tagline" | "heroHeadline" | "heroSubheadline" | "heroMockupUrl" | "vatNote" | "disclaimer" | "secondaryCtaLabel" | "secondaryCtaUrl"> & { tagline: string; heroHeadline: string; heroSubheadline: string; heroMockupUrl: string; vatNote: string; disclaimer: string; secondaryCtaLabel: string; secondaryCtaUrl: string; tiers: FormTier[]; trustPoints: string[]; stats: { value: string; label: string }[]; benefits: Item[]; highlights: Item[]; steps: Item[]; faqs: { question: string; answer: string }[] };
const emptyTier = (): FormTier => ({ name: "", description: "", priceMonthly: 0, badge: "", isRecommended: false, displayOrder: 0, isActive: true, features: [""] });
const emptyForm: Form = { name: "", slug: "", shortDescription: "", imageUrl: "", isActive: false, displayOrder: 0, tagline: "", heroHeadline: "", heroSubheadline: "", heroMockupUrl: "", trustPoints: [], stats: [], benefits: [], highlights: [], steps: [], faqs: [], vatNote: "", disclaimer: "", secondaryCtaLabel: "", secondaryCtaUrl: "", tiers: [emptyTier()] };
const listOf = (value: unknown) => Array.isArray(value) ? value : [];
const slugify = (value: string) => value.toLocaleLowerCase("tr-TR").replace(/[çğıöşü]/g, (c) => ({ ç: "c", ğ: "g", ı: "i", ö: "o", ş: "s", ü: "u" })[c] ?? c).normalize("NFKD").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const formatPrice = (cents: number) => new Intl.NumberFormat("tr-TR", { style: "currency", currency: "TRY" }).format(cents / 100);
const input = "mt-1 w-full rounded-xl border border-corp-border bg-white p-2.5 text-sm outline-none focus:border-corp-teal";

function TextList({ values, onChange, limit, placeholder }: { values: string[]; onChange: (values: string[]) => void; limit: number; placeholder: string }) { return <div className="grid gap-2">{values.map((value, index) => <div className="flex gap-2" key={`${index}-${value}`}><input maxLength={120} value={value} onChange={(e) => onChange(values.map((item, i) => i === index ? e.target.value : item))} placeholder={placeholder} className={input} /><button type="button" onClick={() => onChange(values.filter((_, i) => i !== index))} aria-label="Satırı sil" className="text-red-600"><Trash2 size={16} /></button></div>)}{values.length < limit && <button type="button" onClick={() => onChange([...values, ""])} className="inline-flex w-fit items-center gap-1 text-sm font-semibold text-corp-teal"><Plus size={16} /> Ekle</button>}</div>; }
function IconSelect({ value, onChange }: { value?: string; onChange: (value: string) => void }) { const Icon = getPlanIcon(value); return <label className="flex items-center gap-2"><Icon size={18} className="text-corp-teal" /><select value={value || "Sparkles"} onChange={(e) => onChange(e.target.value)} className={input}>{PLAN_ICON_NAMES.map((name) => <option key={name}>{name}</option>)}</select></label>; }
function ItemList({ values, onChange, limit, kind }: { values: Item[]; onChange: (values: Item[]) => void; limit: number; kind: "icon" | "plain" }) { return <div className="grid gap-3">{values.map((item, index) => <div key={index} className="rounded-xl border border-corp-border bg-white p-3"><div className="grid gap-2 md:grid-cols-[180px_1fr]">{kind === "icon" && <IconSelect value={item.icon} onChange={(icon) => onChange(values.map((v, i) => i === index ? { ...v, icon } : v))} />}<input maxLength={80} value={item.title} onChange={(e) => onChange(values.map((v, i) => i === index ? { ...v, title: e.target.value } : v))} placeholder="Başlık" className={input} /></div><textarea maxLength={300} value={item.description} onChange={(e) => onChange(values.map((v, i) => i === index ? { ...v, description: e.target.value } : v))} placeholder="Açıklama" className={`${input} min-h-20`} /><div className="flex items-center justify-between text-xs text-corp-gray"><span>{item.description.length}/300</span><button type="button" onClick={() => onChange(values.filter((_, i) => i !== index))} className="text-red-600">Sil</button></div></div>)}{values.length < limit && <button type="button" onClick={() => onChange([...values, { icon: "Sparkles", title: "", description: "" }])} className="inline-flex w-fit items-center gap-1 text-sm font-semibold text-corp-teal"><Plus size={16} /> Ekle</button>}</div>; }

export default function AdminProductsPage() {
  const [plans, setPlans] = useState<Plan[]>([]), [query, setQuery] = useState(""), [editing, setEditing] = useState<Plan | null>(null), [open, setOpen] = useState(false), [form, setForm] = useState<Form>(emptyForm), [slugEdited, setSlugEdited] = useState(false), [error, setError] = useState(""), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [uploading, setUploading] = useState(false), [confirmDelete, setConfirmDelete] = useState<Plan | null>(null);
  async function load() { setLoading(true); const response = await fetch("/api/admin/plans"); const data = await response.json(); if (response.ok) setPlans(data); else setError(data.error ?? "Ürünler yüklenemedi"); setLoading(false); }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => plans.filter((plan) => `${plan.name} ${plan.slug}`.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"))), [plans, query]);
  const update = <K extends keyof Form>(key: K, value: Form[K]) => setForm((current) => ({ ...current, [key]: value }));
  function openForm(plan?: Plan) { setEditing(plan ?? null); setOpen(true); setForm(plan ? { ...emptyForm, ...plan, trustPoints: listOf(plan.trustPoints).map(String), stats: listOf(plan.stats) as Form["stats"], benefits: listOf(plan.benefits) as Form["benefits"], highlights: listOf(plan.highlights) as Form["highlights"], steps: listOf(plan.steps) as Form["steps"], faqs: listOf(plan.faqs) as Form["faqs"], tiers: plan.tiers?.map((tier) => ({ ...tier, priceMonthly: tier.priceMonthly / 100, description: tier.description ?? "", badge: tier.badge ?? "", features: listOf(tier.features).map(String) })) ?? [emptyTier()] } : emptyForm); setSlugEdited(Boolean(plan)); setError(""); }
  function updateTier(index: number, patch: Partial<FormTier>) { update("tiers", form.tiers.map((tier, i) => i === index ? { ...tier, ...patch } : tier)); }
  async function upload(file: File, key: "imageUrl" | "heroMockupUrl") { if (!file.type.startsWith("image/") || file.size > 5 * 1024 * 1024) return setError("Yalnızca 5 MB'a kadar görsel dosyaları yüklenebilir."); setUploading(true); const body = new FormData(); body.append("file", file); const response = await fetch("/api/admin/plans/upload", { method: "POST", body }); const data = await response.json(); if (response.ok) update(key, data.url); else setError(data.error ?? "Görsel yüklenemedi."); setUploading(false); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); setSaving(true); const payload = { ...form, slug: form.slug || slugify(form.name), priceMonthly: Math.round((form.tiers[0]?.priceMonthly || 0) * 100), features: [], fullContentHtml: "", tiers: form.tiers.map((tier, index) => ({ ...tier, priceMonthly: Math.round(tier.priceMonthly * 100) / 100, displayOrder: index, features: tier.features.map((item) => item.trim()).filter(Boolean) })) }; const response = await fetch(editing ? `/api/admin/plans/${editing.id}` : "/api/admin/plans", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) setError(data.error ?? "Kaydetme başarısız."); else { setOpen(false); setEditing(null); setForm(emptyForm); await load(); } setSaving(false); }
  async function toggle(plan: Plan) { await fetch(`/api/admin/plans/${plan.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ isActive: !plan.isActive }) }); await load(); }
  async function remove() { if (!confirmDelete) return; const response = await fetch(`/api/admin/plans/${confirmDelete.id}`, { method: "DELETE" }); const data = await response.json(); setConfirmDelete(null); if (!response.ok) setError(data.error ?? "Ürün silinemedi."); else await load(); }
  return <div className="flex flex-col gap-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/admin" className="mb-2 inline-flex items-center gap-2 text-sm text-corp-gray"><ArrowLeft size={16} /> Admin</Link><h1 className="font-display text-2xl font-bold text-corp-charcoal">Abonelik Ürünleri</h1><p className="text-sm text-corp-gray">Yapılandırılmış ürün sayfalarını ve fiyat paketlerini yönetin.</p></div><button onClick={() => openForm()} className="inline-flex items-center gap-2 rounded-xl bg-corp-teal px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16} /> Yeni Ürün Ekle</button></header>
    {error && <div role="alert" className="flex justify-between rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700"><span>{error}</span><button onClick={() => setError("")} aria-label="Kapat"><X size={16} /></button></div>}
    <section className="rounded-3xl border border-corp-border bg-white p-5 shadow-luxury"><div className="mb-5 flex max-w-md gap-2"><Search className="mt-2 text-corp-gray" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="İsim veya slug ara..." className={input} /></div><div className="overflow-x-auto"><table className="w-full min-w-[750px] text-left text-sm"><thead><tr className="border-b border-corp-border text-xs uppercase tracking-wider text-corp-gray"><th className="p-3">Ürün</th><th className="p-3">Paketler</th><th className="p-3">Durum</th><th /></tr></thead><tbody>{loading ? <tr><td colSpan={4} className="p-8 text-center">Yükleniyor...</td></tr> : filtered.map((plan) => <tr key={plan.id} className="border-b border-corp-border"><td className="p-3"><div className="font-semibold">{plan.name}</div><div className="text-xs text-corp-gray">{plan.slug}</div></td><td className="p-3">{plan.tiers?.length ?? 0} paket</td><td className="p-3"><button onClick={() => void toggle(plan)} className="rounded-full bg-corp-surface px-3 py-1 text-xs">{plan.isActive ? "Aktif" : "Pasif"}</button></td><td className="p-3 text-right"><button onClick={() => openForm(plan)} className="mr-3 text-corp-teal">Düzenle</button><button onClick={() => setConfirmDelete(plan)} className="text-red-600">Sil</button></td></tr>)}</tbody></table></div></section>
    {open && <section className="rounded-3xl border border-corp-border bg-white p-6 shadow-luxury"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">{editing ? "Ürünü Düzenle" : "Yeni Ürün"}</h2><button onClick={() => setOpen(false)} aria-label="Formu kapat"><X /></button></div><form onSubmit={submit} className="grid gap-6"><fieldset className="grid gap-3 rounded-2xl border border-corp-border p-4 md:grid-cols-2"><legend className="px-2 font-semibold">Genel</legend><label>Ürün adı<input required maxLength={120} value={form.name} onChange={(e) => { update("name", e.target.value); if (!slugEdited) update("slug", slugify(e.target.value)); }} className={input} /></label><label>Slug<input required value={form.slug} onChange={(e) => { setSlugEdited(true); update("slug", slugify(e.target.value)); }} className={input} /></label><label className="md:col-span-2">Kısa açıklama<input required maxLength={200} value={form.shortDescription} onChange={(e) => update("shortDescription", e.target.value)} className={input} /></label><label>Sıralama<input type="number" min="0" value={form.displayOrder} onChange={(e) => update("displayOrder", Number(e.target.value))} className={input} /></label><label className="flex items-center gap-2 pt-7"><input type="checkbox" checked={form.isActive} onChange={(e) => update("isActive", e.target.checked)} /> Aktif</label></fieldset>
      <fieldset className="grid gap-3 rounded-2xl border border-corp-border p-4 md:grid-cols-2"><legend className="px-2 font-semibold">Hero</legend><label>Etiket<input maxLength={120} value={form.tagline} onChange={(e) => update("tagline", e.target.value)} className={input} /></label><label>Hero başlık<input maxLength={80} value={form.heroHeadline} onChange={(e) => update("heroHeadline", e.target.value)} className={input} /></label><label className="md:col-span-2">Hero alt başlık<textarea maxLength={300} value={form.heroSubheadline} onChange={(e) => update("heroSubheadline", e.target.value)} className={`${input} min-h-20`} /></label><label className="md:col-span-2">Ürün logosu / ikonu (sayfada küçük gösterilir)<input type="url" value={form.imageUrl ?? ""} onChange={(e) => update("imageUrl", e.target.value)} className={input} /></label><label className="md:col-span-2">Hero ekran görüntüsü<input type="url" value={form.heroMockupUrl} onChange={(e) => update("heroMockupUrl", e.target.value)} className={input} /><label className="mt-2 inline-flex cursor-pointer items-center gap-2 text-sm text-corp-teal"><ImagePlus size={16} />{uploading ? "Yükleniyor..." : "Görsel yükle"}<input type="file" accept="image/*" className="sr-only" onChange={(e) => e.target.files?.[0] && void upload(e.target.files[0], "heroMockupUrl")} /></label></label><div className="md:col-span-2"><p className="mb-2 text-sm font-medium">Güven maddeleri</p><TextList values={form.trustPoints} onChange={(value) => update("trustPoints", value)} limit={5} placeholder="Kısa güven maddesi" /></div></fieldset>
      <fieldset className="rounded-2xl border border-corp-border p-4"><legend className="px-2 font-semibold">Faydalar</legend><ItemList values={form.benefits} onChange={(value) => update("benefits", value)} limit={6} kind="icon" /></fieldset><fieldset className="rounded-2xl border border-corp-border p-4"><legend className="px-2 font-semibold">Öne çıkan özellikler</legend><ItemList values={form.highlights} onChange={(value) => update("highlights", value)} limit={8} kind="icon" /></fieldset>
      <fieldset className="rounded-2xl border border-corp-border p-4"><legend className="px-2 font-semibold">Adımlar</legend><ItemList values={form.steps} onChange={(value) => update("steps", value as Form["steps"]) } limit={5} kind="plain" /></fieldset><fieldset className="rounded-2xl border border-corp-border p-4"><legend className="px-2 font-semibold">SSS</legend><div className="grid gap-3">{form.faqs.map((faq, index) => <div key={index} className="rounded-xl border p-3"><input maxLength={80} value={faq.question} onChange={(e) => update("faqs", form.faqs.map((v, i) => i === index ? { ...v, question: e.target.value } : v))} placeholder="Soru" className={input} /><textarea maxLength={800} value={faq.answer} onChange={(e) => update("faqs", form.faqs.map((v, i) => i === index ? { ...v, answer: e.target.value } : v))} placeholder="Cevap" className={`${input} min-h-24`} /><button type="button" onClick={() => update("faqs", form.faqs.filter((_, i) => i !== index))} className="text-sm text-red-600">Sil</button></div>)}{form.faqs.length < 10 && <button type="button" onClick={() => update("faqs", [...form.faqs, { question: "", answer: "" }])} className="inline-flex w-fit items-center gap-1 text-sm font-semibold text-corp-teal"><Plus size={16} /> SSS ekle</button>}</div></fieldset>
      <fieldset className="grid gap-3 rounded-2xl border border-corp-border p-4 md:grid-cols-2"><legend className="px-2 font-semibold">Ek ayarlar</legend><label>KDV notu<input maxLength={160} value={form.vatNote} onChange={(e) => update("vatNote", e.target.value)} className={input} /></label><label>İkincil CTA etiketi<input maxLength={80} value={form.secondaryCtaLabel} onChange={(e) => update("secondaryCtaLabel", e.target.value)} className={input} /></label><label>İkincil CTA URL<input value={form.secondaryCtaUrl} onChange={(e) => update("secondaryCtaUrl", e.target.value)} placeholder="https://, mailto:, tel: veya /" className={input} /></label><label className="md:col-span-2">Yasal uyarı<textarea maxLength={800} value={form.disclaimer} onChange={(e) => update("disclaimer", e.target.value)} className={`${input} min-h-20`} /></label></fieldset>
      <fieldset className="rounded-2xl border border-corp-border bg-corp-surface p-4"><legend className="px-2 font-semibold">Paketler</legend><div className="grid gap-3">{form.tiers.map((tier, index) => <div key={tier.id ?? index} className="rounded-xl border bg-white p-4"><div className="mb-3 flex justify-between"><strong>Paket {index + 1}</strong><button type="button" onClick={() => form.tiers.length > 1 && update("tiers", form.tiers.filter((_, i) => i !== index))} className="text-sm text-red-600">Sil</button></div><div className="grid gap-3 md:grid-cols-2"><label>Ad<input required value={tier.name} onChange={(e) => updateTier(index, { name: e.target.value })} className={input} /></label><label>Fiyat (TL)<input required type="number" min="0.01" step="0.01" value={tier.priceMonthly || ""} onChange={(e) => updateTier(index, { priceMonthly: Number(e.target.value) })} className={input} /></label><label className="md:col-span-2">Kimler için (kısa açıklama)<input maxLength={300} value={tier.description ?? ""} onChange={(e) => updateTier(index, { description: e.target.value })} className={input} /></label><label>Rozet<input maxLength={80} value={tier.badge ?? ""} onChange={(e) => updateTier(index, { badge: e.target.value })} className={input} /></label><label className="flex items-center gap-2 pt-7"><input type="checkbox" checked={tier.isRecommended} onChange={(e) => update("tiers", form.tiers.map((v, i) => ({ ...v, isRecommended: e.target.checked && i === index })))} /> Önerilen</label><div className="md:col-span-2"><TextList values={tier.features} onChange={(features) => updateTier(index, { features })} limit={20} placeholder="Paket özelliği" /></div></div></div>)}</div><button type="button" onClick={() => update("tiers", [...form.tiers, { ...emptyTier(), displayOrder: form.tiers.length }])} className="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-corp-teal"><Plus size={16} /> Paket ekle</button></fieldset>
      <div className="flex flex-wrap justify-end gap-3"><button type="button" onClick={() => editing && window.open(`/services/ai-automation/${editing.slug}?preview=1`, "_blank", "noopener,noreferrer")} disabled={!editing} className="rounded-xl border px-4 py-2 text-sm disabled:opacity-40">Sayfayı önizle</button><button disabled={saving} className="rounded-xl bg-corp-teal px-5 py-2.5 text-sm font-semibold text-white">{saving ? "Kaydediliyor..." : "Kaydet"}</button></div></form></section>}
    {confirmDelete && <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6"><h2 className="text-lg font-bold">Ürün silinsin mi?</h2><p className="mt-2 text-sm">“{confirmDelete.name}” kalıcı olarak silinecek.</p><div className="mt-5 flex justify-end gap-2"><button onClick={() => setConfirmDelete(null)} className="rounded-xl border px-4 py-2">Vazgeç</button><button onClick={() => void remove()} className="rounded-xl bg-red-600 px-4 py-2 font-semibold text-white">Sil</button></div></div></div>}
  </div>;
}
