require('dotenv').config();
const cron = require('node-cron');
const { PrismaClient } = require('@prisma/client');
const { PrismaPg } = require('@prisma/adapter-pg');
const pg = require('pg');
const { GoogleGenerativeAI } = require('@google/generative-ai');

const getPrismaClient = () => {
  const dbUrl = process.env.DATABASE_URL;
  if (dbUrl && (dbUrl.startsWith("postgres://") || dbUrl.startsWith("postgresql://"))) {
    const pool = new pg.Pool({ connectionString: dbUrl });
    const adapter = new PrismaPg(pool);
    return new PrismaClient({ adapter });
  }
  return new PrismaClient();
};

const prisma = getPrismaClient();

// User provided explicitly:
// API Key: AIzaSyDUbbnNti8FplVUfM2oI5QlXUc4nd3mWI4
// Project Name: projects/10969532610
const apiKey = process.env.GEMINI_API_KEY || "AIzaSyDUbbnNti8FplVUfM2oI5QlXUc4nd3mWI4";
const genAI = new GoogleGenerativeAI(apiKey);

const TOPICS = [
  "Son teknoloji haberleri ve yazilim dunyasindaki gelismeler",
  "Yapay zekanin medya ve reklamcilik sektorune etkileri",
  "Dijital pazarlama ve gerilla pazarlama stratejileri",
  "E-ticaret siteleri icin donusum artirma taktikleri",
  "Siber guvenlik onlemleri ve kurumsal verilerin korunmasi"
];

function getRandomTopic() {
  return TOPICS[Math.floor(Math.random() * TOPICS.length)];
}

function generateSlug(title) {
  return title.toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .trim() + '-' + Math.random().toString(36).substring(2, 6);
}

async function generateAndPublishBlog() {
  console.log(`[${new Date().toISOString()}] Otonom Blog Uretimi Basliyor...`);

  const topic = getRandomTopic();
  console.log(`Secilen Konu: ${topic}`);

  const prompt = `Sen "Cicekana Teknoloji & Medya" isimli kurumsal bir firmanin bas yazari ve teknoloji uzmanisin.
Gorev: Asagidaki konu hakkinda oldukca guncel, SEO uyumlu, ilgi cekici ve bilgilendirici bir blog yazisi olustur.
Konu: ${topic}
Kurallar:
1. Ilk satir mutlaka "# " ile baslayan yaratici ve dikkat cekici bir baslik olmali.
2. Yazi dili profesyonel ama anlasilir (kurumsal blog dili) olmali.
3. Icerik markdown formatinda olmali. Alt basliklar (##, ###) kullan.
4. Yazi en az 300-400 kelime civarinda dolgun bir icerik olmali.
5. Sonunda mutlaka Cicekana Teknoloji & Medya'nin sundugu ilgili hizmetlere (ornegin e-ticaret, yazilim, reklam) ufak bir cagri (call-to-action) yap.
Onemli Not: Sen yaziyi uretirken normal duzgun Turkce dil kurallarina uyarak uret. Sadece benim bu promptumda ozel karakterler yok.`;

  try {
    console.log("Gemini'den icerik bekleniyor...");
    const model = genAI.getGenerativeModel({ model: "gemini-pro" });
    const result = await model.generateContent(prompt);
    const response = await result.response;
    let content = response.text();
    
    let title = "Guncel Teknoloji ve Medya Haberleri";
    const titleMatch = content.match(/^#\s+(.+)$/m);
    if (titleMatch && titleMatch[1]) {
      title = titleMatch[1].trim();
      content = content.replace(/^#\s+.+\n*/m, '');
    }

    const slug = generateSlug(title);
    
    let author = await prisma.user.findFirst({ where: { role: 'SUPER_ADMIN' } });
    if (!author) {
      author = await prisma.user.create({
        data: {
          email: 'admin@cicekana.com',
          name: 'Cicekana Admin',
          role: 'SUPER_ADMIN',
          passwordHash: 'AUTOGENERATED'
        }
      });
    }

    const postData = {
      title: title,
      slug: slug,
      content: { body: content }, 
      excerpt: content.substring(0, 150).replace(/[#*`]/g, '') + '...',
      category: "Teknoloji & Medya",
      status: "PUBLISHED",
      publishedAt: new Date(),
      authorId: author.id,
      readTime: Math.max(3, Math.floor(content.split(' ').length / 200)),
      metaDescription: title.substring(0, 160),
    };

    try {
      const post = await prisma.blogPost.create({
        data: postData
      });
      console.log(`✅ Basariyla yayinlandi! ID: ${post.id} | Baslik: ${title}`);
    } catch (dbError) {
      console.error("Veritabanina kaydedilirken hata olustu:", dbError.message);
    }

  } catch (error) {
    console.error("Gemini API Hatasi:", error);
  }
}

console.log("Otonom Blogger servisi baslatildi. Gorev her gun 09:00 ve 21:00'de calisacak sekilde ayarlandi.");
cron.schedule('0 9,21 * * *', () => {
  generateAndPublishBlog();
});

generateAndPublishBlog();
